# Generated by Django 3.1.1 on 2020-09-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Todo',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='alias',
            new_name='description',
        ),
    ]
